### ISSUE TITLE
Follow-up interviews with Unbound

### ISSUE THREAD

**Issue by iteles** [dwyl/video#29]
A couple of months ago we carried out an agile training workshop with Unbound.

Now that they have had a chance to integrate the practices we taught them, it's time that we get in touch and ask them what was implemented, how it has been working for them and understand how valuable the training was for them.

**Tasks:**
+ [x] Get in touch asking if we can do little follow-up interviews on camera
+ [x] Write the possible questions/script (both must-haves and a few indicator questions if the conversation goes in that direction)
+ [ ] Organise a time and date
+ [ ] Gather the equipment and conduct the interviews
+ [ ] Edit this into a video that we can splice with our video of the training itself

Doesn't have to be done TODAY (so not a priority 1) but really very high priority for us or it'll be too late!
cc @sohilpandya

**Comment by nelsonic** [comment]
@iteles IMO _after_ https://github.com/dwyl/hq/issues/321 and https://github.com/dwyl/hq/issues/229 this _should_ be the next highest priority item ... 
**Video** with ***testimonials*** from **clients** is the _single_ most engaging content we can put on the (_services_) Website.

**Comment by iteles** [comment]
@nelsonic Agreed. As I say, this isn't a TODAY task, it's pretty clear from all the hq issues that the finance issues are the top priority, but is next on the list (which is what I meant by 'really very high' priority).

I think we need to rethink how we use priority 1 labels. I currently have [19 priority 1 issues assigned to me](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+assignee%3Aiteles+label%3Apriority-1+) which means I have trouble paying attention to them. I would like to move to priority-2 as 'the most important tasks', priority-3 for 'next in line' and priority-1 for 'this is a danger to the organisation'. I'll open an issue :+1:

**Comment by ghost** [comment]
Have reached out to Hannah

**Comment by iteles** [comment]
@markwilliamfirth You'll need to speak to Charlie separately because https://twitter.com/superhighfives/status/869515803883917312

**Comment by iteles** [comment]
@markwilliamfirth Also, this would be a pretty cool event to attend and take notes on! https://generalassemb.ly/education/the-ultimate-guide-to-video-marketing/london/37064

**Comment by iteles** [comment]
@markwilliamfirth Did you hear back from Hannah?

**Comment by Cleop** [comment]
**What?**
A video giving insight into what it is like to take part in a dwyl training workshop, more specifically a dwyl agile training workshop.

**Why?**
In order to help prospective clients understand the services that dwyl offers and to decipher whether they may appeal to their needs.

**Duration?**
3-5mins?

**Who is our primary target audience?**
Prospective clients

**How?**
- Featuring our signature intro/outro logo and title slides
- Shot using our in-house camera, sound and lighting at Unbound?
- Interview/ talking head style
- With a voiceover over any cut aways of action - do we have any footage from the training itself or might we have to reenact some action shots?
- It will not be scripted as we want organic responses from the attendees however we will provide them with question prompts to help them feel comfortable and to know roughly what it is we're interested in covering.

**Question prompts:** - we need to discuss which of these are most important and which of these are better covered in text on the website

**The Basics - to be answered by a dwyler**
- What kind of workshops and training does dwyl offer?
- How long do they last?
- What size groups do you work with?
- How technical do my team need to be to have one?

**For the Unbound team**:
- What do Unbound do?
- What workshop did you have?
- How long was the workshop?
- Why did you choose to do this workshop?
- What happened on the day?
- How did you find the experience?
- What did you enjoy?
- What did you learn?
- What did you find more challenging or not enjoy?
- Would you do the workshop again?
- Would you recommend the workshop to others?
- What have the team used or applied anything they learnt?
- How did you find the technical level of the course? Was it accessible enough? Was it sophisticated enough?

**Things to remember:**
- Always tell the interviewee that there are no wrong or right answers
- Encourage them to look at the interviewer not the camera and to forget that the camera is there
- Ask them to begin their answers by incorporating the question so although the interviewer will prompt them with a question they should answer it fully e.g.
**What we don't want**
Q: What is your name?
Ans: Cleo
**What we do want**
Q: What is your name?
Ans: My name is Cleo
So that in the edit the question can be cut out but it still makes sense without it!
- Take cutaway shots of things in the space or close ups of their hands etc so you can edit their speech in the cut if you need to make things more brief but it won't look jumpy
- Remember the rule of thirds, frame someone's eyes along the 2/3 height line.

**Questions to discuss/answer:**
- How much do we want this to be a testimonial on the **agile** workshop that Unbound experienced and how much do we want this to be a video on **dwyl's workshops** featuring a testimonial from Unbound?
- In what contexts do we expect to use this? - is the dwyl site the only place or might it be shown in a talk/presentation? or elsewhere? where?
- How long do we want it to be?
- Is it possible for us to shoot it at Unbound? Otherwise can they come to us?
- Where can we shoot people who may no longer work at Unbound?
- How many from people from Unbound took part or could take part in the video?
- Who led the workshop from dwyl? It would be nice to have these people talking about what we do

@iteles @nelsonic @sohilpandya - would be great to get any feedback on the questions above for discussion to help shape these ideas.

**Comment by nelsonic** [comment]
@Cleop LGTM! 👍
